### ISSUE TITLE
CTD FOR MY FRIEND WHEN HE ENTERS ANY BUILDING

### ISSUE THREAD

**Issue by toni-rana** [Para0x/Fahdon-A-Skyrim-Together-Experience#10]
[modlist.txt](https://github.com/Para0x/Fahdon-A-Skyrim-Together-Experience/files/12261591/modlist.txt)

**Describe the bug**
Everytime my friend goes into a cell his game freezes on the loading screen and crashes, but this doesnt happen when he is on the server by himself only when i join. 

I can go inside any building i want without crashin be it alone or with him

**To Reproduce**

1. Make server using teamtogether.gg
2. both people join server
3. both people go into an interior eg embershad mine
4. game crashes for one of the people

**Expected behavior**
no one crashes and we can see eachother ingame

**Modlist version**
 2.1.0

**Did you add any additional mods?**
Updated skyrim together reborn to 1.5.0

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
Updated skyrim together reborn to 1.5.0

**Comment by Para0x** [comment]
1.5.0 is not stable, thus not recommended to use. That's likely the cause of the CTD.
