### ISSUE TITLE
Trouble during install

### ISSUE THREAD

**Issue by amm2448** [Para0x/Fahdon-A-Skyrim-Together-Experience#3]
Just installed almost all mods through wabbajack and it cannot find markarth HD retexture or xLODGen.94.7z files to download. Markarth HD has been deleted and cannot find anywhere. Any help would be much appreciated!

**Comment by LinusKall** [comment]
Hello!

You can get these files in the ``fahdon-support`` channel in the [``The Animonculory``](https://discord.gg/DffHKcszfg) discord server. The download links can be found in the first pinned message (atm).

I would post the links here, but I don't know if I'm allowed to, so I'll avoid doing so.

**Comment by Para0x** [comment]
Resolved.
