### ISSUE TITLE
Trouble downloading the modpack from wabajack.

### ISSUE THREAD

**Issue by HolyBajaBlast** [Para0x/Fahdon-A-Skyrim-Together-Experience#4]
I was asking for help because of a download issue on the wabajack discord and they said there was a problem with the wabajack file on the server and to contact you.

**Comment by Para0x** [comment]
No worries! You can find the missing downloads in the pins of the Fahdon support channel. Feel free to ping me in the support channel as well if you need assistance @HolyBajaBlast . I will be closing this issue for now!
